### ISSUE TITLE
Configure protected master/trunk branch on Github for twisted/twisted

### ISSUE THREAD

**Issue by adiroiban** [twisted-infra/braid#146] opened 2015-11-05 11:16 UTC
We should protect merged to master  ... after we have a buildbot builder which reports the status

https://help.github.com/articles/about-protected-branches/

**Comment by adiroiban** [comment] 2015-12-30 17:05
this is related to #147

**Comment by hawkowl** [comment] 2016-05-10 16:15
I've made it protected from force push so far.

**Comment by rodrigc** [comment] 2016-05-17 19:17
@hawkowl @glyph Is there anything left to do on this item, or can it be closed out?

**Comment by hawkowl** [comment] 2016-05-18 02:09
We still need to make Buildbot report the status to github to prevent broken merges.

**Comment by adiroiban** [comment] 2016-05-18 06:42
This depends on #147  ... now we need to agree how to configure the status ... one status for each builder or an aggregated for all buildbot builders

**Comment by rodrigc** [comment] 2016-06-05 09:29
I recommend closing this ticket.

**Comment by adiroiban** [comment] 2016-06-05 10:40
Why?

Since we now have travis-ci, we can at least set up protected branched based on travis-ci 

is better than noting.

and in the future we can also add coverage status to protect the trunk

**Comment by rodrigc** [comment] 2016-06-05 10:45
@hawkowl configured protection from forced push: https://github.com/twisted-infra/braid/issues/146#issuecomment-218209872

That seems good enough to me.  I don't think it is worth doing the other things you mention, hence I recommend closing this ticket.

**Comment by adiroiban** [comment] 2016-06-05 10:48
If we don't protect the trunk for travis-ci we will end up with travis tests being broken in trunk and nobody will care about fixing them when buildbot is green... and then all PR commit will fail even if the changes in the PR are ok.

**Comment by rodrigc** [comment] 2016-06-05 10:53
I don't believe that will happen.  People can see the Travis results now in the PR and and are doing a good job of merging things without breaking the trunk.  Protecting against fast forward to trunk is good enough.  Hence I recommend closing this issue.

**Comment by glyph** [comment] 2016-06-06 07:30
@adiroiban - I do think we should do this eventually, maybe even soon, but I'd like to see a couple of weeks worth of build reliability data from Travis at first.

**Comment by glyph** [comment] 2016-06-06 07:32
To elaborate: when we status-protect trunk, I want to ensure that we are confident that travis is building reliably.  I do not want to enable status protection and have it be a major annoyance while we work out the kinks with the new travis build infrastructure.

**Comment by tomprince** [comment] 2016-06-06 16:00
@glyph: I would agree if it wasn't really easy to turn status protection back off if/when it is a problem.

**Comment by Lukasa** [comment] 2016-06-21 08:11
I'm with @tomprince and @adiroiban here: just turn it on. It's literally a switch to disable it, and administrators such as @glyph can override the barrier anyway and do whatever they want: the UI just shouts at them.

**Comment by glyph** [comment] 2016-06-21 08:21
Seeing the recent broken commits on trunk has convinced me.  Status protection is now on.  In the interest of preserving our lessons learned, I'm not going to force-push them off of trunk, but we should avoid ever doing that again :).

**Closed by glyph** 2016-06-21 08:21 UTC

**Comment by rodrigc** [comment] 2016-06-21 20:51
@glyph @adiroiban
I had a patch which passed buildbot, and got code review approval from @wsanchez

I then tried to follow these instructions: https://twistedmatrix.com/trac/wiki/ReviewProcess#Authors:Howtomergethechangetotrunk

Specifically what I did was:

```
git checkout trunk
git merge --no-ff 8378-rodrigc-assert
tox  -e py27-tests-posix
```

I then did:

```
git push origin trunk
```

but got this message:

```
git push origin trunk
Counting objects: 1, done.
Writing objects: 100% (1/1), 291 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/trunk.
remote: error: 2 of 3 required status checks are expected
To https://github.com/twisted/twisted
 ! [remote rejected] trunk -> trunk (protected branch hook declined)
error: failed to push some refs to 'https://github.com/twisted/twisted'
```

What is the full procedure to get a merge committed?

Thanks.

**Comment by adiroiban** [comment] 2016-06-21 21:59
Hi,

I think that we should not enable codecov status check, just yet.

I have disabled them. travis-ci is the only status left

@rodrigc please try again. Thanks!

**Comment by rodrigc** [comment] 2016-06-21 22:04
I tried `git push origin trunk`, and it still failed, but with a slightly different error message:

```
Counting objects: 1, done.
Writing objects: 100% (1/1), 291 bytes | 0 bytes/s, done.
Total 1 (delta 0), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/trunk.
remote: error: Required status check "continuous-integration/travis-ci" is expected
To https://github.com/twisted/twisted
 ! [remote rejected] trunk -> trunk (protected branch hook declined)
error: failed to push some refs to 'https://github.com/twisted/twisted'
```

**Comment by adiroiban** [comment] 2016-06-21 22:08
So.. I assume that you are trying to merge this 

https://github.com/twisted/twisted/commits/8378-rodrigc-assert which has a PR

https://github.com/twisted/twisted/pull/94

In the PR you should see that it can not be merged... as it is out of date. Please sync with master and wait for tests.

I think that before trying to merge anything, the PR should be green and you should see the merge button as green... and I think that you can also merge right away from the GitHub UI as it should not hurt :)

Thanks!

**Comment by rodrigc** [comment] 2016-06-21 22:32
@adiroiban 

I did the following.

1. Went to https://github.com/twisted/twisted
2. Clicked on branch dropdown, and entered:  **8378-rodrigc-assert**
3. Next to the branch dropdown, I saw a link  **View #94**
4.  I clicked on **View #94**
5.  On the screen, I saw that the branch was out of date.  I clicked on the link **Update Branch**
6.  This kicked off a Travis build which succeeded, and the status was green.
7. After the Travis build succeeded, I clicked on **Merge Branch** to perform the final merge.
8. The merge succeeded: https://github.com/twisted/twisted/commit/0de84dd0c2e76ccbfe5377aaf22412b7ed5dda7a

Based on what I am seeing, I would recommend that the Twisted project
update the documentation at  https://twistedmatrix.com/trac/wiki/ReviewProcess#Authors:Howtomergethechangetotrunk
to use the GitHub UI when doing the merge.  It is much easier to follow
through the UI where the problem areas are, and how to solve them.

When using the command-line, it is hard to figure out the problem preventing the merge.

Also, can you review the merge, and make sure that I followed all the right steps and merged properly?

Thanks for your support.

**Comment by adiroiban** [comment] 2016-06-21 22:59
Well, it depend on how you roll :) 

We should still support merging from the command line.

Please note that the wiki page is just describing the general review process and it should be as VCS agnostic as possible.

I was able to sync/update with master, merge in trunk, add a commit message and push from the command line :)

Please note that  this is not the standard commit message.

```
Merge pull request #94 from rodrigc/8378-rodrigc-assert
    
    
    Author: rodrigc
    Reviewer: wsanchez
    Fixes: #8378
```

**Comment by rodrigc** [comment] 2016-06-21 23:22
Yes I know about that, I accidentally forgot to modify the default merge commit message provided by GitHub.
I still feel that documenting the GitHub UI for merging would make things easier for users.
The commit you did was fairly simple, with no out of date branch or merge conflict.

Plus, you are changing the backend infrastructure so you are familiar with what is going on.
For developers, the cryptic error messages when things go wrong is confusing.
At least the UI provides more useful feedback as to how to correct the problem.

**Comment by adiroiban** [comment] 2016-06-21 23:26
The problem with current configuration, is that if you don't create a PR for your branch the Travis-CI build will not be triggered ... so in the end we might want to enable Travis-CI build for every commit especially since we are planning to do the same with Buildbot builds

**Comment by rodrigc** [comment] 2016-06-22 00:32
I think steering devs in the direction of creating PRs for things destined for trunk is OK, especially if it facilitates working with Travis.
Travis is now becoming a "gate" for getting things into trunk.
We'll see how well it scales and also how Twisted devs will accept the workflow.

**Comment by glyph** [comment] 2016-06-22 08:08
@adiroiban - why did you disable the codecov check?

**Comment by adiroiban** [comment] 2016-06-23 08:14
I have disabled codecov since I thought that we are still just experimenting with it.
I have created a ticket to look at better communicating that codecov is official https://twistedmatrix.com/trac/ticket/8494

**Comment by rodrigc** [comment] 2016-06-23 16:42
@adiroiban @glyph 
I received review approval for https://github.com/twisted/twisted/pull/206
Travis has built it successfully.  Codecov looks stuck.  It hasn't run, and since it is **Required**, I cannot merge this PR.

If I look at https://codecov.io/gh/twisted/twisted/pull/206 , I see **Unable to retrieve commit from GitHub API. Please check that your bot user has authorization to twisted/twisted.**

I tried to contact codecov support at https://gitter.im/codecov/support?source=all-rooms-list , but they didn't respond yet.

Any ideas as to how to proceed?

**Comment by adiroiban** [comment] 2016-06-23 17:39
I would say that we should skip codecov for now.

It has a history of being broken :( 

I don't know what is wrong with our branch... I would say nothing is wrong :)

I am also testing codecov.io for my project which is about the same size as Twisted and codecov is not working. 

@rodrigc I tried to have codecov disabled but @glyph was -1 on this .

**Comment by adiroiban** [comment] 2016-06-23 17:58
I tried to re-build the travis-ci ... maybe it will re-trigger codecov status update :)

**Comment by rodrigc** [comment] 2016-06-23 19:17
@adiroiban @glyph 
Is it possible to enable codecov, but remove the **Required** flag for the Twisted project?
That way the coverage results can be seen if codecov runs properly, but if it gets stuck,
it won't block doing commits.

Right now, I am blocked because codecov is not running at all.

That's a different story from having codecov running, and then telling me that my patch has not enough coverage.

**Comment by glyph** [comment] 2016-06-23 20:48
@rodrigc Did you run the buildbots? It's the buildbots that report coverage data, not travis.

**Comment by rodrigc** [comment] 2016-06-23 20:52
@glyph the buildbots ran, but there seems to be something *stuck* with codecov.io.  Look at https://github.com/twisted/twisted/pull/206 near the bottom of the page where it says: **Some checks haven’t completed yet**

**Comment by glyph** [comment] 2016-06-23 20:59
@rodrigc I think the problem is that the hashes don't line up.  for some reason the buildbot thinks it's testing df56189 but the PR page reports c022722 as the top commit.  Both have the commit message "Add topfile", so I don't know what's going on here.

**Comment by glyph** [comment] 2016-06-23 21:01
Oh. The commit IDs _are_ different.  Apparently you rebased something?

Don't use rebase, kids.  Stay in school.

```
$ git show origin/pr/206
commit c0227226393d57829c4bda186f9ea5912f6b3bce
Author: Craig Rodrigues <rodrigc@FreeBSD.org>
Date:   Wed Jun 22 19:16:58 2016 -0700

    Add topfile

diff --git a/twisted/topfiles/8493.misc b/twisted/topfiles/8493.misc
new file mode 100644
index 0000000..e69de29
$ git show origin/8493-rodrigc-none
commit df561896b01d83f8e7168af0d5eae4ef31c8cc19
Author: Craig Rodrigues <rodrigc@FreeBSD.org>
Date:   Wed Jun 22 19:16:58 2016 -0700

    Add topfile

diff --git a/twisted/topfiles/8493.misc b/twisted/topfiles/8493.misc
new file mode 100644
index 0000000..e69de29
```

**Comment by wsanchez** [comment] 2016-06-23 21:08
git: all the rope you could possibly need to kill yourself with

	-wsv

**Comment by rodrigc** [comment] 2016-06-23 21:13
OK, I will re-run the buildbot with the correct github ID.
I think this will be less confusing when @adiroiban finishes https://github.com/twisted-infra/braid/issues/202

**Comment by glyph** [comment] 2016-06-23 21:16
@rodrigc Yep. In the meanwhile, you can make it less confusing by getting rid of your fork and just doing development and creating PRs for branches in the twisted/twisted namespace.  Given our access-control model for buildbot right now, there's potential confusion for 3rd-party work, but you can just push your branches directly and be sure that the PR refers to the same git object.

**Comment by glyph** [comment] 2016-06-23 21:16
Or, stop using rebase :)

**Comment by rodrigc** [comment] 2016-06-23 21:27
I would rather keep my own fork and do development there, so that I have the same experience
as contributors who are not Twisted project members who submit via pull requests.
That is incentive to improve things, so that outside contributors have a better experience.

**Comment by glyph** [comment] 2016-06-23 23:12
By all means!

**Comment by glyph** [comment] 2016-06-23 23:13
I feel like I should point out though: self-torture is not the same thing as "incentive to improve things".  Right now we have a situation where many core developers (myself included) are so burnt out on dealing with the papercuts that our process requires and maintaining its infrastructure that we don't have any energy left to make things better.  It is OK to just know about a problem but make it easier for yourself so you have energy left over to fix it at some point.  You don't have to force yourself to suffer it every day ;)

**Comment by adiroiban** [comment] 2016-06-24 13:59
From what I can see, codecov.io uses some heuristic technique to determine when all reports are sent for a branch.

buildbot is sending about 10 reports... and travis is also sending 4 reports so I think that when buildbot is not triggered, it will wait for buildbot reports to be sent... and forget to give up if no reports are sent :)

I was able to get a valid PR once buildbot coverage reports were sent.

**Comment by hawkowl** [comment] 2016-06-28 12:18
I have disabled the travis-ci requirement -- branches that arent going through PRs don't run on Travis.

**Comment by hawkowl** [comment] 2016-06-28 12:22
Although I guess it seems that everything goes through travis, so turned it back on...

**Comment by adiroiban** [comment] 2016-06-28 12:22
@hawkowl I have a ticket in review in which I am enabling Travis-CI build for all pushed... so that Travis-CI are builds even if we don't have a PR

once that is merge we can always force travis-ci

and I think that we should force Travis-CI:

1. To make sure we don't accidentally break the travis-ci tests and make a hard like for non-team members
2. To prevent team members to accidcentally commit without running the tests

there is also a PR to send buildbot status to GitHub so that we can also enforce based on buildbot runs

**Comment by glyph** [comment] 2016-06-29 00:27
Let's please go ahead and enable travis for all branches, at least until the PR list becomes the review queue (and hopefully that just means we'll have fewer branches...)

**Comment by adiroiban** [comment] 2016-06-29 00:57
I have this ticket waiting for review which enables travis-ci for all branches and enforces patchcoverage to 100% https://twistedmatrix.com/trac/ticket/8494 :)

**Comment by adiroiban** [comment] 2016-06-29 16:56
travis-ci is now enabled for all branches on push
