### ISSUE TITLE
twistedmatrix.com serves expired cert when not using SNI

### ISSUE THREAD

**Issue by alex** [twisted-infra/braid#241] opened 2017-07-28 17:54 UTC
```
~ ❯❯❯ openssl s_client -connect twistedmatrix.com:443 | openssl x509 -text -noout
depth=1 /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
verify error:num=20:unable to get local issuer certificate
verify return:0
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            03:b9:be:76:f8:26:f4:b3:40:4a:5e:76:cc:76:60:8c:82:c2
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3
        Validity
            Not Before: Mar 23 07:01:00 2017 GMT
            Not After : Jun 21 07:01:00 2017 GMT
```

with SNI it's fine:

```
~ ❯❯❯ openssl s_client -connect twistedmatrix.com:443 -servername twistedmatrix.com | openssl x509 -text -noout
depth=1 /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
verify error:num=20:unable to get local issuer certificate
verify return:0
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            04:65:f7:3f:89:74:20:3d:15:26:23:25:8c:61:81:c0:a6:9d
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=Let's Encrypt, CN=Let's Encrypt Authority X3
        Validity
            Not Before: Jul 21 17:55:00 2017 GMT
            Not After : Oct 19 17:55:00 2017 GMT
```

it should either error out if SNI is required, or it should serve a valid cert

**Comment by glyph** [comment] 2017-07-28 19:02
This was caused by a manual `cp` instead of an `ln`. It should be fixed now.

**Closed by glyph** 2017-07-28 19:02 UTC

**Comment by glyph** [comment] 2017-07-28 19:03
Thanks for reporting it!
