### ISSUE TITLE
(source) links in API docs are broken

### ISSUE THREAD

**Issue by twm** [twisted-infra/braid#196] opened 2016-05-14 04:31 UTC
For example, the [(source)](http://twistedmatrix.com/trac/browser/tags/releases/twisted-16.1.1/twisted/python/filepath.py#L417) at https://twistedmatrix.com/documents/current/api/twisted.python.filepath.AbstractFilePath.html#descendant.

**Comment by hawkowl** [comment] 2016-05-18 13:31
The latest docs have the correct URL; we need some redirector for the historical ones.

**Comment by rodrigc** [comment] 2016-05-20 17:49
This is a duplicate of https://github.com/twisted-infra/braid/issues/148

**Comment by adiroiban** [comment] 2016-05-20 18:12
closed as duplicate of #148

**Closed by adiroiban** 2016-05-20 18:12 UTC
